### ISSUE TITLE
官网的CDN坏了，很多css和js没法下载

### ISSUE THREAD

**Issue by riveralan** [staringos/mtbird#16]
![image](https://user-images.githubusercontent.com/14345488/230789077-9e1a7dc1-0893-48c4-a4f0-2cc40531eeca.png)

**Comment by riveralan** [comment]
![image](https://user-images.githubusercontent.com/14345488/230789110-f424efef-8125-43cd-8a67-d7b56d35c9a6.png)

**Comment by georgezouq** [comment]
https证书过期了，已修复
