### ISSUE TITLE
pnpm  -w run start 无法启动

### ISSUE THREAD

**Issue by SmithJson** [staringos/mtbird#33]
非常感谢您的开源项目，我根据 README.md 提示进行操作，发现启动不了，希望能帮助解决下

### 问题描述
在 mtbird 目录执行 pnpm install 后，执行 pnpm -w run start 报错

### 环境
Mac 13.4.1
pnpm 8.6.9
node 16.20.0
npm 8.19.4

### 截图
![image](https://github.com/staringos/mtbird/assets/40036121/e9a512ef-3987-4d2d-9bab-049ba4389b35)

**Comment by liushuai529** [comment]
同样问题,求大神回复
环境
macos 12.6.5
node v16.17.1
pnpm 7.29.1
npm 8.19.2

**Comment by jtaox** [comment]
node版本切到18以上试试

**Comment by SmithJson** [comment]
> node版本切到18以上试试

感谢，切换到 node 18.3.0 之后项目可用正常启动了
